#%RAML 1.0 NamedExample

{ 
   "communication":[ 
      { 
         "communicationId":2,
         "contactId":1,
         "communicationType":"email",
         "value":"bfe@sample.com",
         "preferred":true
      }
   ]
}